language: c

os: linux
dist: trusty
sudo: required

services:
  - docker

cache:
  directories:
    - node_modules/

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tools/apt-get-install-deps.sh; fi
  - npm install
  - ls node_modules/.bin

script:
  - tools/travis_script.py

matrix:
  include:
    - env:
      - JOBNAME="Linux/x86-64 Build & Correctness Tests"
      - OPTS="host-linux"
      - RUN_DOCKER=yes
    - env:
      - JOBNAME="Linux/x86-64 without snapshot Build & Correctness Tests"
      - OPTS="no-snapshot"
      - RUN_DOCKER=yes
    - env:
      - JOBNAME="Raspberry Pi 2 Build Test"
      - OPTS="rpi2"
      - RUN_DOCKER=yes
    - env:
      - JOBNAME="Linux/x86-64 without snapshot Build & Correctness Tests"
      - OPTS="no-snapshot"
      - RUN_DOCKER=yes
    - env:
      - JOBNAME="OSX/x86-64 Build & Correctness Tests"
      - OPTS="host-darwin"
      os: osx
      install: tools/brew-install-deps.sh

fast_finish: true