language: c

os: linux
dist: trusty
sudo: required

services:
  - docker

cache:
  directories:
    - node_modules/

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tools/apt-get-install-deps.sh; fi
  - npm install
  - ls node_modules/.bin

script:
  - npm run lint
  - tools/travis_script.py

matrix:
  include:
    - env:
      - JOBNAME="Linux/x86-64 Build & Correctness Tests"
      - OPTS="host-linux"
      - RUN_DOCKER=yes
    - env:
      - JOBNAME="Linux/x86-64 without snapshot Build & Correctness Tests"
      - OPTS="no-snapshot"
      - RUN_DOCKER=yes
    - env:
      - JOBNAME="Linux/x86-64 without snapshot Build & Correctness Tests"
      - OPTS="no-snapshot"
      - RUN_DOCKER=yes
    - env:
      - JOBNAME="OSX/x86-64 Build & Correctness Tests"
      - OPTS="host-darwin"
      os: osx
      install: tools/brew-install-deps.sh

before_deploy:
  - git config --local user.name "yorkie"
  - git config --local user.email "yorkiefixer@gmail.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  privider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  on:
    tags: true

fast_finish: true
