language: c

os: linux
dist: trusty
sudo: required

cache:
  directories:
    - node_modules/

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tools/apt-get-install-deps.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then tools/brew-install-deps.sh; fi
  - npm install
  - ls node_modules/.bin

script:
  - npm run lint && tools/build.py --tests --no-check-valgrind

env:
  matrix:
    - OPTS="host-linux" TARGET_OS="linux"
    - OPTS="--test=external-modules"
    - OPTS="--test=no-snapshot"

matrix:
  include:
    - os: osx
      env: OPTS="--test=host-darwin"
  fast_finish: true
